export const MOCK_USERS = [
  {
    id: 'mock-renu-001',
    full_name: 'Renu Sharma',
    avatar_url: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?w=150&h=150&fit=crop',
    bio: 'Certified Bharatanatyam performer with 12 years of experience. Trained under Kalakshetra Foundation. I love sharing the beauty of classical Indian dance with enthusiastic learners.',
    location: 'Chennai, Tamil Nadu',
    skills_offered: ['Bharatanatyam', 'Kathak', 'Classical Dance Theory'],
    skills_wanted: ['Guitar', 'Yoga', 'Web Development'],
    portfolio_links: ['https://renu-dance.com', 'https://youtube.com/renusharma'],
    learning_streak: 24,
    total_sessions: 38,
    avg_rating: 4.9,
    review_count: 31,
    is_verified: true,
    role: 'user',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-08-01T10:00:00Z',
  },
  {
    id: 'mock-arjun-002',
    full_name: 'Arjun Mehta',
    avatar_url: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?w=150&h=150&fit=crop',
    bio: 'Computer Science student at IIT Bombay. Currently learning advanced Java and exploring backend development. Fluent in Python and competitive programming.',
    location: 'Mumbai, Maharashtra',
    skills_offered: ['Python', 'Competitive Programming', 'Data Analysis'],
    skills_wanted: ['Java Programming', 'Spring Boot', 'System Design'],
    portfolio_links: ['https://github.com/arjunmehta', 'https://linkedin.com/in/arjunmehta'],
    learning_streak: 12,
    total_sessions: 15,
    avg_rating: 4.6,
    review_count: 12,
    is_verified: false,
    role: 'user',
    created_at: '2024-02-10T10:00:00Z',
    updated_at: '2024-07-20T10:00:00Z',
  },
  {
    id: 'mock-priya-003',
    full_name: 'Priya Nair',
    avatar_url: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?w=150&h=150&fit=crop',
    bio: 'UI/UX Designer with 4 years of freelance experience. Passionate about user-centered design, accessibility and design systems. I break down complex design concepts into simple lessons.',
    location: 'Bangalore, Karnataka',
    skills_offered: ['UI/UX Design', 'Figma', 'Adobe XD', 'Design Systems'],
    skills_wanted: ['React.js', 'Machine Learning', 'Photography'],
    portfolio_links: ['https://priya-designs.io', 'https://behance.net/priyanair'],
    learning_streak: 18,
    total_sessions: 42,
    avg_rating: 4.8,
    review_count: 38,
    is_verified: true,
    role: 'user',
    created_at: '2024-01-28T10:00:00Z',
    updated_at: '2024-08-05T10:00:00Z',
  },
  {
    id: 'mock-vikram-004',
    full_name: 'Vikram Singh',
    avatar_url: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?w=150&h=150&fit=crop',
    bio: 'Guitar teacher with 8 years of experience teaching acoustic and electric guitar. Also teaches music theory. Currently learning Java for mobile app development.',
    location: 'Delhi, India',
    skills_offered: ['Guitar', 'Piano', 'Music Theory'],
    skills_wanted: ['Java Programming', 'Android Development'],
    portfolio_links: ['https://soundcloud.com/vikramsingh'],
    learning_streak: 30,
    total_sessions: 55,
    avg_rating: 4.7,
    review_count: 46,
    is_verified: true,
    role: 'user',
    created_at: '2023-11-05T10:00:00Z',
    updated_at: '2024-08-10T10:00:00Z',
  },
  {
    id: 'mock-sneha-005',
    full_name: 'Sneha Patel',
    avatar_url: 'https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?w=150&h=150&fit=crop',
    bio: 'Yoga instructor and wellness coach. 200-hour certified in Hatha and Vinyasa yoga. Teaching online and in-person. Learning content writing to expand my blog.',
    location: 'Pune, Maharashtra',
    skills_offered: ['Yoga', 'Meditation', 'Breathing Techniques'],
    skills_wanted: ['Content Writing', 'Photography', 'Video Editing'],
    portfolio_links: ['https://snehaomyoga.com'],
    learning_streak: 45,
    total_sessions: 67,
    avg_rating: 4.9,
    review_count: 60,
    is_verified: true,
    role: 'user',
    created_at: '2023-10-12T10:00:00Z',
    updated_at: '2024-08-12T10:00:00Z',
  },
];

export const MOCK_SESSIONS = [
  {
    id: 'sess-001',
    mentor_id: 'mock-renu-001',
    learner_id: 'mock-arjun-002',
    skill: 'Bharatanatyam',
    skill_category: 'Dance & Arts',
    scheduled_at: '2024-08-20T14:00:00Z',
    duration_minutes: 60,
    status: 'accepted',
    meeting_link: 'https://meet.google.com/mock-link',
    notes: 'Focus on basic adavus and hand gestures',
    mentor_notes: '',
    mentor: MOCK_USERS[0],
    learner: MOCK_USERS[1],
    created_at: '2024-08-15T10:00:00Z',
  },
  {
    id: 'sess-002',
    mentor_id: 'mock-priya-003',
    learner_id: 'mock-arjun-002',
    skill: 'UI/UX Design',
    skill_category: 'Design & Arts',
    scheduled_at: '2024-07-10T11:00:00Z',
    duration_minutes: 90,
    status: 'completed',
    meeting_link: 'https://meet.google.com/mock-link-2',
    notes: 'Introduction to Figma and wireframing',
    mentor_notes: 'Good session, Arjun picks up concepts fast',
    mentor: MOCK_USERS[2],
    learner: MOCK_USERS[1],
    created_at: '2024-07-05T10:00:00Z',
  },
  {
    id: 'sess-003',
    mentor_id: 'mock-vikram-004',
    learner_id: 'mock-priya-003',
    skill: 'Guitar',
    skill_category: 'Music',
    scheduled_at: '2024-08-25T16:00:00Z',
    duration_minutes: 60,
    status: 'pending',
    meeting_link: '',
    notes: 'Beginner chords and strumming patterns',
    mentor_notes: '',
    mentor: MOCK_USERS[3],
    learner: MOCK_USERS[2],
    created_at: '2024-08-18T10:00:00Z',
  },
];

export const MOCK_REVIEWS = [
  {
    id: 'rev-001',
    session_id: 'sess-002',
    reviewer_id: 'mock-arjun-002',
    reviewee_id: 'mock-priya-003',
    rating: 5,
    comment: 'Priya is an excellent teacher. She explained Figma from scratch in a very organized way. Highly recommend for anyone starting with UI design.',
    reviewer: MOCK_USERS[1],
    reviewee: MOCK_USERS[2],
    created_at: '2024-07-11T10:00:00Z',
  },
  {
    id: 'rev-002',
    session_id: 'sess-001',
    reviewer_id: 'mock-arjun-002',
    reviewee_id: 'mock-renu-001',
    rating: 5,
    comment: 'Renu teacher is incredibly patient and knowledgeable. The way she teaches mudras is very systematic. Looking forward to more sessions!',
    reviewer: MOCK_USERS[1],
    reviewee: MOCK_USERS[0],
    created_at: '2024-08-22T10:00:00Z',
  },
  {
    id: 'rev-003',
    session_id: 'sess-003',
    reviewer_id: 'mock-priya-003',
    reviewee_id: 'mock-vikram-004',
    rating: 4,
    comment: 'Vikram is a great guitar teacher. Very encouraging and covers basics very well. The session was productive.',
    reviewer: MOCK_USERS[2],
    reviewee: MOCK_USERS[3],
    created_at: '2024-08-26T10:00:00Z',
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'notif-001',
    type: 'booking',
    title: 'New booking request',
    message: 'Priya Nair has requested a UI/UX Design session with you.',
    is_read: false,
    created_at: '2024-08-18T09:30:00Z',
  },
  {
    id: 'notif-002',
    type: 'session',
    title: 'Session reminder',
    message: 'Your Bharatanatyam session with Renu Sharma starts in 1 hour.',
    is_read: false,
    created_at: '2024-08-20T13:00:00Z',
  },
  {
    id: 'notif-003',
    type: 'review',
    title: 'New review received',
    message: 'Arjun Mehta left you a 5-star review for the UI/UX Design session.',
    is_read: true,
    created_at: '2024-07-11T10:05:00Z',
  },
  {
    id: 'notif-004',
    type: 'connection',
    title: 'Profile viewed',
    message: 'Sneha Patel viewed your profile and is interested in your skills.',
    is_read: true,
    created_at: '2024-08-15T14:20:00Z',
  },
  {
    id: 'notif-005',
    type: 'booking',
    title: 'Session accepted',
    message: 'Renu Sharma accepted your booking request for Bharatanatyam.',
    is_read: false,
    created_at: '2024-08-16T11:00:00Z',
  },
];

export const MOCK_DISCUSSIONS = [
  {
    id: 'disc-001',
    author_id: 'mock-renu-001',
    title: 'Best resources for learning classical dance online?',
    content: 'Hi everyone! I have been teaching Bharatanatyam for over a decade and I want to share some resources for beginners. What online platforms or YouTube channels do you recommend for learners who are just starting out?',
    category: 'Resources',
    likes: 18,
    replies_count: 7,
    author: MOCK_USERS[0],
    created_at: '2024-08-10T10:00:00Z',
  },
  {
    id: 'disc-002',
    author_id: 'mock-arjun-002',
    title: 'Java vs Python for backend - which to learn first?',
    content: 'I am a 2nd year CS student trying to decide between investing time in Java Spring Boot or Python Django for backend web development. Both have good job prospects. Looking for advice from experienced devs here.',
    category: 'Technology',
    likes: 24,
    replies_count: 12,
    author: MOCK_USERS[1],
    created_at: '2024-08-12T14:00:00Z',
  },
  {
    id: 'disc-003',
    author_id: 'mock-priya-003',
    title: 'How SkillSwap changed my learning journey',
    content: 'Six months ago I joined SkillSwap looking for someone to teach me guitar. I ended up teaching UI/UX Design to 8 different learners in exchange. The peer-to-peer model is incredibly effective because you both stay motivated.',
    category: 'Stories',
    likes: 42,
    replies_count: 15,
    author: MOCK_USERS[2],
    created_at: '2024-08-14T09:00:00Z',
  },
  {
    id: 'disc-004',
    author_id: 'mock-vikram-004',
    title: 'Tips for teaching music online effectively',
    content: 'Teaching guitar online has its challenges - latency, audio quality, demonstrating technique. Here are 5 things I have learned after 3 years of online music teaching that make sessions much better.',
    category: 'Teaching Tips',
    likes: 31,
    replies_count: 9,
    author: MOCK_USERS[3],
    created_at: '2024-08-16T16:00:00Z',
  },
  {
    id: 'disc-005',
    author_id: 'mock-sneha-005',
    title: 'Morning yoga routine for desk workers - free guide',
    content: 'As a yoga instructor I see many students with back pain and poor posture from sitting all day. Here is a free 15-minute morning routine that helps. Happy to answer questions or do a live session for anyone interested!',
    category: 'Health & Fitness',
    likes: 56,
    replies_count: 20,
    author: MOCK_USERS[4],
    created_at: '2024-08-18T07:00:00Z',
  },
];

export const SKILL_CATEGORIES = [
  'All',
  'Technology',
  'Design & Arts',
  'Dance & Arts',
  'Music',
  'Language',
  'Health & Fitness',
  'Academic',
  'Communication',
  'Creative',
  'Lifestyle',
];

export const BADGES_DATA = [
  { badge_type: 'streak', badge_name: 'Consistent Learner', badge_description: 'Maintained a 7-day streak' },
  { badge_type: 'sessions', badge_name: 'Session Star', badge_description: 'Completed 10 sessions' },
  { badge_type: 'rating', badge_name: 'Top Rated', badge_description: 'Maintained 4.8+ rating' },
  { badge_type: 'community', badge_name: 'Community Helper', badge_description: 'Made 20 discussion contributions' },
  { badge_type: 'first', badge_name: 'First Swap', badge_description: 'Completed first skill exchange' },
];
